const data = [
  {
    place: "Holendrecht",
    text: "Dit station is de thuisbasis van de Holendrechtse rapformatie ‘Zone 6’. De frontman van Zone 6, Joey AK, zit sinds vorig jaar vast wegens ontvoering en mishandeling. In de tussentijd heeft zijn rechterhand, Bigidagoe, het stokje van hem overgenomen.Toen de mannen van Zone 6 in de in de middag van 26 augustus 2020 naar verluidt zich in Amsterdam Zuid begaven, ontstond er een onverwachte schietpartij. Bij deze schietpartij werd de rapper-en-ondernemer Bigidagoe meerdere malen geraakt en overgebracht naar het ziekenhuis. Diezelfde nacht werden er, niet geheel toevallig in diezelfde straat in Zuid, schoten gelost op het huis van een rivaal: rapper-en-ondernemer ‘Justin van Zuid’.Toen in de nacht erop de moeder van Bigidagoe hier om de hoek in haar woning lag te slapen werd het huis doelwit van een schietoefening. Het huis van de nietsvermoedende moeder werd doorboord met acht kogels en de buurt schrok zich rot. Het is niet duidelijk of de ruzie nu gesetteld is.",
    image_src: "https://cdn.nos.nl/image/2021/03/12/723111/2880x2160a.jpg",
    safety_index: "121",
    bron: "https://axed.nl/beschoten-woning-amsterdam-zuid-blijkt-van-19-jarige-rapper/",
  },
  {
    place: "Bullewijk",
    text: "Op het bedrijventerrein twee blokken verder was er op de zondagochtend van 1 augustus 2021 een schietpartij. Oud-profvoetballer Jergé Hoefdraad (35) werd daarbij levensgevaarlijk gewond. Hij overleed dinsdag aan zijn verwondingen. Hoefdraad werd zondag voor 6 uur door zijn hoofd geschoten op een feest in een pand aan de Stekkenbergweg, op bedrijventerrein Amstel III-Bullewijk, niet ver van het AMC. Volgens de politie had hij geprobeerd een ruzie te beëindigen door ‘ertussen te springen’. Op beelden die rondgaan op sociale media, zouden twee knallen te horen zijn. Andere beelden zouden een vriendin tonen die smeekt het noodnummer 112 te bellen, terwijl ze Hoefdraads hoofd vasthoudt en zijn naam roept. Hij werd in kritieke toestand naar het ziekenhuis gebracht. De 34-jarige verdachte is maandagavond door Belgische politiemensen aangehouden in Bocholt, vlak bij de grens met Nederland.",
    image_src: "https://cdn.nos.nl/image/2021/12/08/810103/1280x720a.jpg",
    safety_index: "106",
    bron: "https://www.demorgen.be/nieuws/nederlandse-oud-profvoetballer-overleden-na-schietpartij-verdachte-opgepakt-in-belgie~bd6fe36e/?referrer=https%3A%2F%2Fwww.google.com%2F",
  },
  {
    place: "Bijlmer",
    text: "Thea Moear, ‘The Godmother'. Moear was de dochter van de legendarische ‘Blonde Greet’ (Gijsje Balk), die door haar heroïnesmokkel een bekende verschijning in het Amsterdamse criminele circuit was. Thea wist dus hoe het was om makkelijk geld te verdienen, maar ze pakte het zelf wat slimmer aan. Moear was vrijwel vanaf het begin betrokken bij het drugsimperium van Klaas Bruinsma dat opgericht werd in het midden van de jaren zeventig, een groot en gewelddadig misdaadsyndicaat. Zij besloot wie er in de organisatie niet te vertrouwen was om ze vervolgens uit de weg te laten ruimen. Na de liquidatie van Klaas Bruinsma in 1991 vertrok Moear naar Panama, waar ze in 2000 werd gearresteerd wegens het smokkelen van partijen drugs naar Europa. Na vijf jaar in de Panamese gevangenis kwam ‘The Godmother’ terug naar haar geboorteplaats Amsterdam waar ze in de Bijlmermeer haar moeder tot haar dood verzorgde. Nu is Moear 72 en woont ze zelf in een van de Bijlmerse flats.",
    image_src: "https://cdn.nos.nl/image/2021/03/12/723111/2880x2160a.jpg",
    safety_index: "118",
    bron: "https://panorama.nl/artikel/307314/crime-to-go-in-gesprek-met-the-godmother-van-de-penoze-thea-moear",
  },
  {
    place: "Strandvliet",
    text: "Dit metrostation heeft een aparte ligging die met regelmaat zorgt voor confrontaties tussen supportersgroepen van Ajax en de bezoekende supportersgroep. De uitgang van het metrostation Strandvliet loopt namelijk naar de ingang van de Amsterdam Arena en de oprit naar het supportershonk van Ajax.  Op 9 maart 2014 begint het al in het centrum van de stad, waar Cambuur supporters provocerende liederen scanderen. Het is dan ook bij de Nieuwmarkt waar de supportersgroepen voor de eerste keer met elkaar op de vuist gaan. Naar aanleiding van wat er in het centrum plaatsvond, stappen een kleine 100 Cambuur hooligans uit bij metrostation Strandvliet en gaan daar op zoek naar Ajax hooligans. Ze vinden ongeveer twintig Ajaxsupporters bij hun supportershome en gaan met ze op de vuist.  Wanneer de ME arriveert ontstaat er zo’n grote chaos dat de agenten hun wapen moeten trekken en waarschuwingsschoten moeten lossen. De agenten hebben het gevoel dat ze de laatste linie zijn tussen de kolkende hooligan-menigte en de vaders en moeders met kinderen die achter hun de Arena proberen te betreden.",
    image_src: "https://cdn.nos.nl/image/2021/03/12/723111/2880x2160a.jpg",
    safety_index: "110",
    bron: "https://www.ajaxshowtime.com/bijzaken-en-geruchten/ongeregeldheden-fans-ajax-en-cambuur.html",
  },
  {
    place: "Duivendrecht",
    text: "De laatste zaak waar Peter R. de Vries zich over boog voordat hij op tragische wijze in de leidsedwarsstraat werd geliquideerd was een merkwaardige. Peter R. sprak over deze zaak bij zijn laatste Boulevard-uitzending en deelde zijn afschuw. Een vader staat op 1 oktober 2019 met zijn peuterende dochtertje achterin de auto geparkeerd aan de buitensingel in Duivendrecht, zo'n twee minuten van dit station verwijderd. Omwonenden merken dat de bestuurder, de vader, niet beweegt en proberen contact met hem te leggen. Tevergeefs. Omstanders bellen de hulpdiensten die op hun beurt op het plaats delict arriveren. Het slachtoffer wordt met een schotwond door zijn hoofd aangetroffen en door het geweer in zijn hand wordt er uitgegaan van een zelfmoord. Het bleek een goed gefatsoeneerde kapper met een blanco strafblad. Mede door een kritische blik van Peter R. werd er vanuit andere invalshoeken naar de zaak gekeken, waardoor er een heel andere kant van het verhaal aan het licht kwam. De beste vriend van het slachtoffer, aan wie het slachtoffer geld had geleend, is nu veroordeeld voor 12 jaar cel.",
    image_src: "https://cdn.nos.nl/image/2021/03/12/723111/2880x2160a.jpg",
    safety_index: "127",
    bron: "https://www.ad.nl/binnenland/peuter-op-achterbank-overleeft-moord-op-vader-een-goed-gemanierde-amsterdamse-kapper~a725dcf1e/",
  },
  {
    place: "Van der Madeweg",
    text: "De 38-jarige Joost is op 27 juli 2017 met de metro onderweg naar huis. Hij heeft net nog contact gehad met zijn vriendin als hij in de metro ter hoogte van deze metrohalte, wordt aangevallen door Philip O. O. slaat toe uit het niets, verklaren getuigen. Er was geen ruzie. Geen eerder contact. Niks. Joost is het slachtoffer van een volkomen willekeurige daad. De politie kan O. snel aanhouden, maar voor Joost komt de hulp te laat. Hij bezwijkt aan zijn verwondingen. Philip O. bleek voor de dodelijke steekpartij vaker in de fout is gegaan. Veel vaker. Ook ontstaat een beeld van slechte en onzorgvuldige communicatie tussen verschillende instanties. O. komt voor het eerst in aanraking met Justitie in 2006, als hij nog minderjarig is. Hij krijgt jeugd-TBS opgelegd maar ontloopt zijn straf door naar het buitenland te vluchten. O. verblijft enige tijd in Ghana en Engeland. Ook hier gaat het mis. In Engeland krijgt hij een gevangenisstraf van twee jaar na een mishandeling en hij wordt uiteindelijk het land uitgezet. Als volwassene keert hij terug naar Nederland. Want hoe kon het dat iemand als Philip O., een ernstig verwarde man die op verlof was van een gesloten psychiatrische inrichting, zomaar toe kon slaan? Had O. wel de juiste behandeling gekregen? En waarom mocht hij überhaupt naar buiten?",
    image_src: "https://cdn.nos.nl/image/2021/03/12/723111/2880x2160a.jpg",
    safety_index: "119",
    bron: "https://www.at5.nl/artikelen/183776/reconstructie-had-de-fatale-steekpartij-in-metro-53-voorkomen-kunnen-worden",
  },
  {
    place: "Spaklerweg",
    text: "Stanley Hillis was een van Nederlands’ grootste maffiabazen, hij begon als overvaller en daarmee maakte hij furore in de Amsterdamse onderwereld. Hij draaide daarvoor de bak in waar bleek dat Stanley ook een bekwame uitbreker was. Hij heeft dan ook een aantal keer zichzelf en wat collega’s op spectaculaire wijze uit de gevangenis laten verdwijnen. Een van deze keren was Hilis ontsnapt waarna de politie met grote getalen op zoek was naar hem. Door zijn angst om plots neergeschoten te worden besloot hij zijn verhaal te doen op live televisie bij een talkshow van Sonja Barend. Toen Hillis op 21 februari 2011 bij een afspraak in Amsterdam door de recherche afgeluisterd ging worden, kwam er een busje aanrijden waaruit het vuur werd geopend. De Amsterdamse crimineel werd voor de ogen van een rechercheteam doorzeefd met kogels waarna hij overleed aan zijn verwondingen. Het rechercheteam zette de achtervolging in op het busje en reden door de hele stad heen, tot het team de achtervolging hier op de Spaklerweg plots staakten en hun voertuig omdraaiden. Er werd gedacht dat de politiehelikopter de achtervolging voortzette maar dat was niet het geval. Het apart handelen van de politie is voor sommigen reden geweest om deze liquidatie, een staatsliquidatie te noemen. Op mysterieuze wijze is het busje met verdachten voor het laatst gezien hier op de Spaklerweg.",
    image_src: "https://cdn.nos.nl/image/2021/03/12/723111/2880x2160a.jpg",
    safety_index: "95",
    bron: "https://wnl.tv/2021/02/22/nog-altijd-veel-vragen-over-liquidatie-stanley-hillis-doorzeefd-voor-de-ogen-van-rechercheurs/",
  },
  {
    place: "Amstel",
    text: "Bij de shisha-lounge Fayrouz (zo’n 100 meter van dit station verwijderd) zat de schrik er op de vroege ochtend van 9 maart 2016 goed in. Een student sociologie ging met zijn vriendin heel vroeg in de ochtend naar de sportschool en fietste er bijna tegenaan. Hij keek en keek en belde 112. ‘Jullie moeten zo snel mogelijk hierheen komen. We hebben een hoofd gevonden.’ ‘Is het een mensenhoofd of een dierenhoofd, mijnheer?’ ‘Een mensenhoofd.’ Na tien minuten van veel belangstelling en verontwaardiging bij de vroege vogels in de buurt, kwam de politie. De buurt werd afgezet met linten. Agenten trokken witte pakken aan en zetten zwarte schermen om het hoofd. Na een reeks van liquidaties binnen de stad was het duidelijk dat deze was te linken eraan. De onthoofde Nabil was geen bekende bij de politie, maar bleek na gekraakte berichten door de recherche, samen mijn zijn vrienden uitvoerders te zijn van de verscheidene liquidaties in de stad. De onthoofding was een nieuw uiterste en leek het einde te zijn van een lang lopende Amsterdamse vete.",
    image_src: "https://cdn.nos.nl/image/2021/03/12/723111/2880x2160a.jpg",
    safety_index: "77",
    bron: "https://revu.nl/artikel/448721/er-ligt-een-hoofd-op-straat",
  },
  {
    place: "Wibautstraat",
    text: "Na een voorbereiding van twee jaar werd het plan om de grote Freddy Heineken te ontvoeren bij diens woning in Noordwijk, doordat Heineken een aantal keer niet kwam opdagen, gewijzigd. Volgens het nieuwe plan op 9 november 1983 wachtte de groep ontvoerders hem op buiten zijn oude Heinekenkantoor, hier zo’n 500 meter vandaan op de Wibautstraat. De ontvoerders: Cor van Hout, Willem Holleeder, Frans Meijer en Jan Boellaard zetten de biergigant en zijn chauffeur (Ab Doderer) vast in een Westpoortse loods achter een dubbele wand. Door de langzame communicatie tussen politie en de ontvoerders liep de onderhandeling stroef en duurde het langer dan verwacht. De cellen waar Doderer en Heineken apart werden gehouden waren niet voorzien van enige luxe. Ze zaten vast met handboeien aan de muur en konden nauwelijks vanuit hun bed het chemisch toilet naast hun bed bereiken. Op 30 november 1983 werden, na overhandiging van het gevraagde losgeld, Heineken en Doderer gevonden. De ontvoerders waarvan er intussen 3 uit 4 geliquideerd zijn, werden na een klein kat en muis spel met justities in Frankrijk en Sint-Maarten uitgeleverd aan Nederland. Ze draaiden de bak in en de 15 miljoen losgeld werd deels teruggevonden. Het is nog steeds onduidelijk waar de resterende 8 miljoen losgeld is gebleven.",
    image_src: "https://cdn.nos.nl/image/2021/03/12/723111/2880x2160a.jpg",
    safety_index: "98",
    bron: "https://nl.wikipedia.org/wiki/Ontvoering_van_Freddy_Heineken#Ontvoering",
  },
  {
    place: "Weesperplein",
    text: "In 1972 werd een voormalige bakkerij aan de Weesperzijde 53 (50m van halte weesperplein) te Amsterdam gekraakt door Wernard Bruining en bevriende hippies. Er werd dermate veel gedeald in hasjiesj, geblowd en thee gedronken, dat in 1973 besloten werd er een theehuis van te maken, ook omdat er geen vergunning of diploma voor nodig was. Het theehuis heette: ‘Mellow Yellow’. Een dealer die voor de bar zat en zich voordeed als een klant, verkocht in plastic zakjes voorverpakte hasj en wiet, die bij groothandelaren zoals eerdergenoemde Klaas Bruinsma werd ingekocht. In die beginjaren kon een horecagelegenheid niet gesloten worden alleen maar omdat een klant daar "toevalligerwijze" hasj en wiet verkocht. De hasjvoorraad in de Mellow Yellow werd verstopt achter geheime deuren en luikjes waardoor deze bij verschillende politie-invallen niet in beslag kon worden genomen. Twee jaar later werd in 1975 hetzelfde concept overgenomen door onder andere ‘The Bulldog’, die nu beweren dat zij de eerste coffeeshop waren. In 1978 sloot Mellow Yellow zijn deuren, nadat er brand in het pand was uitgebroken. Bruining zou nog wel hasj leveren aan zijn toenmalige concurrent The Bulldog.",
    image_src: "https://cdn.nos.nl/image/2021/03/12/723111/2880x2160a.jpg",
    safety_index: "98",
    bron: "https://nl.wikipedia.org/wiki/Mellow_Yellow_(coffeeshop)",
  },
];
